version: "3.9"
services:
  my-bank-postgres:
    container_name: my-bank-postgres
    hostname: my-bank-postgres:12.2
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  my-bank-kafka:
    container_name: my-bank-kafka
    hostname: my-bank-kafka
    image: landoop/fast-data-dev:3.3
    ports:
      - "9092:9092"
  my-bank-localstack:
    container_name: my-bank-localstack
    hostname: my-bank-localstack
    image: localstack/localstack:1.3.1
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_SESSION=us-east-1